### ISSUE TITLE
typing_extensions.override is not supported

### ISSUE THREAD

**Issue by Schnouki** [zubanls/zuban#216]
Hey,

I'm working on a Python 3.11 codebase, and considering using zuban with it. The biggest problem is that I get a ton of errors about not using `@override`, while I am in fact using `typing_extensions.override` (since `override` is only available in `typing` since Python 3.12).

Short repro:

```py
from typing_extensions import override

class Foo:
    @override
    def __str__(self) -> str:
        return "<Foo>"
```

Zuban run:
```
$ zuban check --show-error-codes  --python-version=3.11  foobar.py 
foobar.py:6: error: Method "__str__" is not using @override but is overriding a method in class "builtins.object"  [misc]
Found 1 error in 1 file (checked 1 source file)
$ zuban --version
zuban 0.3.0
```

**Comment by davidhalter** [comment]
Thanks!
