### ISSUE TITLE
`zuban` crashes with a **stack overflow** when resolving self-referencing PEP 695 type-parameter

### ISSUE THREAD

**Issue by mvaled** [zubanls/zuban#469]
`zuban` crashes with a **stack overflow** when resolving a PEP 695 type-parameter **default that references its own enclosing class**.  It affects both `zuban check` and the language server's `textDocument/rename`.

### Minimal reproduction

A single line of valid Python (it parses, compiles and runs on CPython ≥ 3.13; at runtime `C.__type_params__[0].__default__ is C`):

```python
class C[T=C]: pass
```

```
$ zuban check x.py
thread 'main' has overflowed its stack
fatal runtime error: stack overflow, aborting
```

It also crashes the language server on a `textDocument/rename` of `C` (or of `T`), and on `zuban mypy x.py`.  `zuban check` alone reproduces it, so the bug is in core type resolution, not the language server.

### Environment

- zuban 0.8.2 — reproduced on the released wheel and on a build of `master` @ `9bcc67883ffeb226f4f810e34100abe4b272575f`.
- Python 3.13+ target (PEP 696 TypeVar defaults); Linux x86_64.

For comparison, mypy 2.1.0 does not crash — it names the problem and recovers:

```
$ mypy x.py
x.py:1: error: Cannot resolve name "C" (possible cyclic definition)  [misc]
x.py:1: error: TypeVar "default" must be a type  [misc]
```

A recursion guard (a "currently-computing" sentinel / depth limit) on the default-resolution path would fix it; mypy's `(possible cyclic definition)` is the corresponding diagnostic.

A regression test is in PR #466.

**Comment by davidhalter** [comment]
Probably related to https://github.com/zubanls/zuban/issues/323
